### ISSUE TITLE
String is not formatted as expected parse node id string

### ISSUE THREAD

**Issue by tronghuybku** [OPCUAUniCT/OPCUAWebPlatformUniCT#20] opened 2020-06-26 05:39 UTC
Hello.I can't read node id. Issue: "String is not formatted as expected parse node id string" in Platform Utils . Can you help me ??

**Comment by msalafia** [comment] 2020-06-26 07:34
The OPC UA WebPlatform uses a regular expression for NodeId validation expressed in the form <nsi>-<id> where <nsi> is the namespace index and <id> is the identifier. The latter can be a number, a string or a guid. The regular expression used is "^(\d+)-(?:(\d+)|(\S+))$" as you can see in [this](https://github.com/OPCUAUniCT/OPCUAWebPlatformUniCT/blob/847e94cbd03a9a220d2789de02576de574b8d856/OPCUA_Web_Platform/OPC%20UA%20Layer/PlatformUtils.cs) code.
Try to check the validity of this regular expression against your nodeId using online tool for regular expression liike [this](https://regex101.com/).
If you don't provide me some examples of strings you are submitting to the platform, i cannot help you.

**Comment by tronghuybku** [comment] 2020-06-26 07:42
Hello! My NodeId ns=2;s=OPC.SimaticNET.TCS

**Comment by msalafia** [comment] 2020-06-26 07:47
If you provide this NodeId in the following format 2-OPC.SimaticNET.TCS it should work.
Look the matching:
![image](https://user-images.githubusercontent.com/11465611/85833461-0aa64b00-b792-11ea-88ca-880e1fcf3f8b.png)

**Comment by tronghuybku** [comment] 2020-06-26 07:51
i don't understand issue ValueToWriteTypeException: Wrong Type Error: String is not formatted as expected (number-yyy where yyy can be string or number or guid)
WebPlatform.Repository.PlatformUtils.ParsePlatformNodeIdString(string str) in PlatformUtils.cs
But i connect another server is OK and find node id ok

**Comment by tronghuybku** [comment] 2020-06-26 07:53
can i send u Server Url and check it or can you teamview help me because i must fix it

**Comment by msalafia** [comment] 2020-06-26 08:00
Write here the url and i will ckeck but not soon. I am busy at the moment.

**Comment by tronghuybku** [comment] 2020-06-26 08:05
thank you. serverurl: opc.tcp://vietscada.com:4852
you must fix in file Config.xml to connect my server
    AutoAcceptUntrustedCertificates: true
    RejectSHA1SignedCertificates: false
    MinimumCertificateKeySize: 1024

**Comment by tronghuybku** [comment] 2020-06-26 08:07
Hope you can solve issue. this is my Graduate thesis so i must fix it. Thank you very much

**Comment by msalafia** [comment] 2020-06-26 08:50
This issue is due to your Node with NodeId "i=2;s=Server Status" because of the space in "Server Status". Space in Node Ids are not so common and quite error prone. If you cannot change the server NodeId i suggest you to change the regular expression with ^(\d+)-(?:(\d+)|([\S ]+))$. It will work.

**Comment by tronghuybku** [comment] 2020-06-26 09:00
It work with Folder. Thank you very much. But when i find node ID variable issue "Wrong ID: There is no Resource with ID 2-TCS:[SeniorStudentHD.Station 1.101]DP,Pump_3_Runtime" . Hope you hope me. nodeID is : "2-TCS:[SeniorStudentHD.Station 1.101]DP,Pump_3_Runtime"

**Comment by msalafia** [comment] 2020-06-26 09:24
All these issues are due to bad NodeId strings. Unfortunately this time the issue is due to a BadNodeIdUnknown and could be due to the sdk call `session.ReadNode(nodeToRead)` or even your server sdk that throws an exception because do not works with this cumbersome nodeId. This is not due to a OPC UA WebPlatform bug so i cannot help you.
I am closing the issue.

**Closed as completed by msalafia** 2020-06-26 09:24 UTC
